services:
  jitsi_mapper:
    image: nordeck/jitsi_mapper
    build:
      context: .
      dockerfile: jcm.Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB.PASS=postgres
      - DB.USER=postgres
      - DB.URL=jdbc:postgresql://postgres_jitsi_mapper/postgres
    depends_on:
      - postgres_jitsi_mapper

  postgres_jitsi_mapper:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_jitsi_mapper_data:/var/lib/postgresql/data

volumes:
  postgres_jitsi_mapper_data:
    name: postgres_jitsi_mapper_data
    driver: local

networks:
  default:
    name: jitsi_mapper_default




