apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-conference-mapper-configmap
type: Opaque
data:
  application.yaml: |
    db.url: jdbc:postgresql://{{ 
            .Chart.Name }}-postgresql:{{ 
            .Values.postgresql.containerPorts.postgresql | default "5432" }}/{{ required "Setting a database name is required!" 
            .Values.postgresql.auth.database }}
    

 # dbUrl: jdbc:postgresql://{{ .Chart.Name }}-postgresql:{{ 1234 | default "5432"}}/{{ required "Setting a database name is required!" .Values.postgresql.auth.database}}
