apiVersion: v2
name: jitsi-conference-mapper
description: A SIP-Call Mapper for Jitsi
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 12.1.3 #chart version
    repository: "https://charts.bitnami.com/bitnami"
