name: Docker Image Build

on:
  push:
    branches:
      - main
      - ${{ github.ref }}
    tags:
      - '*.*.*'

env:
  DOCKER_IMAGE: ghcr.io/nordeck/jitsi-conference-mapper

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      docker-tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          # required for changesets
          fetch-depth: '0'
          # don't persist the credentials so the changesets action doesn't use the
          # github actions token but the git token provided via environment variable
          persist-credentials: false

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}
          labels: |
            org.opencontainers.image.title=Jitsi Conference Mapper
            org.opencontainers.image.description=A mapping application to map Jitsi conference names to PINs and vice versa
            org.opencontainers.image.vendor=Nordeck IT + Consulting GmbH
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      - name: Docker build and push
        uses: docker/build-push-action@v3
        id: dockerBuild
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

