name: Release

on: [workflow_dispatch]

jobs:
  perform_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release branch
        run: git checkout -b main_release
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Push new branch
        run: git push origin main_release
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Prepare Maven release
        run: mvn --batch-mode build-helper:parse-version release:prepare -B -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT -DskipTests
      - name: Maven release
        run: mvn --batch-mode release:perform
      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        with:
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          head: main_release
          base: main
          title: Merge release into main
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              This PR was created in release workflow running.

